export const books = [
  {
    id: 1,
    name: "A Dolls House",
    image: "../../images/images/a-Dolls-house.jpg",
    category: "Fiction",
    author: "John Doe",
    numberOfPages: 20,
    price: 20.5,
  },
  {
    id: 2,
    name: "Faust",
    image: "../../images/images/faust.jpg",
    category: "Non-Fiction",
    author: "Jane Smith",
    numberOfPages: 250,
    price: 15.99,
  },
  {
    id: 3,
    name: "Beloved",
    image: "../../images/images/beloved.jpg",
    category: "Fantasy",
    author: "Emily Brown",
    numberOfPages: 400,
    price: 24.99,
  },
  {
    id: 4,
    name: "Dead Souls",
    image: "../../images/images/dead-souls.jpg",
    category: "Mystery",
    author: "Robert Johnson",
    numberOfPages: 350,
    price: 18.75,
  },
  {
    id: 5,
    name: "Moby Dick",
    image: "../../images/images/moby-dick.jpg",
    category: "Science Fiction",
    author: "Michael Wilson",
    numberOfPages: 30,
    price: 22.0,
  },
];
